# Use an OpenJDK image
FROM openjdk:17-jdk-alpine

# Set the working directory
WORKDIR /app

# Copy the jar file generated by the Spring Boot application
COPY target/My-Ecommerce-0.0.1-SNAPSHOT.jar /app.My-Ecommerce-0.0.1-SNAPSHOT.jar

# Expose the port that the Spring Boot app will run on
EXPOSE 8080

# Command to run the jar filemvn 
ENTRYPOINT ["java", "-jar", "/app.My-Ecommerce-0.0.1-SNAPSHOT.jar"]